 # Copyright (c) 2023, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause


model:
  arch: blip2_vicuna_xinstruct
  model_type: vicuna7b
  load_pretrained: True
  pretrained: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained.pth
  load_finetuned: False
  finetuned: ""
  stage1_url_or_filename: null
  image_model: "eva_clip_g"
  pc_model: "ulip2_pointbert"
  video_model: "eva_clip_g"
  audio_model: "beats"
  pretrained_image_qformer:  https://storage.googleapis.com/sfr-xinstructblip-data-research/model/xinstructblip_checkpoints/vicuna7b_nocue/image_qformer.pth
  pretrained_pc_qformer: https://storage.googleapis.com/sfr-xinstructblip-data-research/model/xinstructblip_checkpoints/vicuna7b_nocue/pc_qformer_last.pth
  pretrained_video_qformer: https://storage.googleapis.com/sfr-xinstructblip-data-research/model/xinstructblip_checkpoints/vicuna7b_nocue/video_qformer.pth
  pretrained_audio_qformer: https://storage.googleapis.com/sfr-xinstructblip-data-research/model/xinstructblip_checkpoints/vicuna7b_nocue/audio_qformer.pth
  load_attention_image_qformer: True
  load_attention_pc_qformer: True
  load_attention_video_qformer: True
  load_attention_audio_qformer: True
  load_ln_type_image: "image"
  load_ln_type_video: "video"
  load_ln_type_audio: "audio"
  load_qformer_type_image: "image"
  load_qformer_type_pc: "pc"
  load_qformer_type_video: "video"
  load_qformer_type_audio: "audio"
  load_projection_image: True
  load_projection_pc: True
  load_projection_video: True
  load_projection_audio: True
  load_projection_type_image: "image"
  load_projection_type_pc: "pc"
  load_projection_type_video: "video"
  load_projection_type_audio: "audio"
  image_encoder_kwargs :  {"image_size": 224, "drop_path_rate": 0, "use_grad_checkpoint": False}
  pc_encoder_kwargs :  {}
  video_encoder_kwargs :   {"image_size": 224, "drop_path_rate": 0, "use_grad_checkpoint": False}
  audio_encoder_kwargs :  {}
  image_precision: "fp16"
  pc_precision: "fp16"
  video_precision: "fp16"
  audio_precision: "fp16"
  freeze_image: True
  freeze_pc: True
  freeze_video: True
  freeze_audio: True
  num_query_token: 32
  llm_model:  "/path/to/vicuna7b"
  prompt:  ""
  max_txt_len: 128
  max_output_txt_len: 256
  apply_lemmatizer: False
  num_few_shot_examples: 0
  few_shot_prob: 0
  qformer_text_input: True
  llm_text_input: True
  modalities :  ["image", "video", "audio", "pc"]
  use_cues: False
  shared_qformer: False
  pretrained_shared_qformer: Null
  load_attention_shared_qformer: False
  load_qformer_type_shared: ""
  load_projection_shared: False
  load_projection_type_shaped: ""
  load_ln_type_shared: ""
  shared_qformer_num_features: 512
  prefix: ""
  postfix: ""
