 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  sherlock_caption: # name of the dataset builder
    data_type: images #extracted features of videos (I3D, VGGish) # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /gallery_tate/wonjae.roh/sherlock_dataset/sherlock_train_v1_1.json
          storage: sherlock/annotations/sherlock_train_v1_1.json
        val:
          url: /gallery_tate/wonjae.roh/sherlock_dataset/sherlock_val_with_split_idxs_v1_1.json
          storage: sherlock/annotations/sherlock_val_with_split_idxs_v1_1.json
        #test:
          #storage: - 
      images:
        storage: sherlock/images
        
