datasets:
  snli_ve:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /export/share/dongxuli/data/lavis/snli/annotation/ve_train.json
          storage: snli/annotations/ve_train.json
        val:
          url: /export/share/dongxuli/data/lavis/snli/annotation/ve_dev.json
          storage: snli/annotations/ve_dev.json
        test:
          url: /export/share/dongxuli/data/lavis/snli/annotation/ve_test.json
          storage: snli/annotations/ve_test.json
      images:
          storage: /export/share/datasets/vision/flickr30k/flickr30k-images
