 # Copyright (c) 2023, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  coin_caption: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]

    vis_processor:
        train:
          name: alpro_video_train
          n_frms: 4
          image_size: 224
          min_scale: 0.9
          max_scale: 1.0
          full_video: False
        eval:
          name: alpro_video_eval
          n_frms: 4
          image_size: 224
          min_scale: 0.9
          max_scale: 1.0
          full_video: False
      
    text_processor:
        train:
          name: blip_caption
        eval:
          name: blip_caption

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: 
            - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/coin/train.json
            # - /export/video-language-dataset/data/coin/annotations/train_lavis.json
          storage: 
            - coin/annotations/train.json
            # - /export/video-language-dataset/data/coin/annotations/train_lavis.json
        val:
          url: 
            - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/coin/val.json
            # - /export/video-language-dataset/data/coin/annotations/val_lavis.json
          storage: 
            - coin/annotations/val.json
            # - /export/video-language-dataset/data/coin/annotations/val_lavis.json
      videos:
        storage: /export/video-language-dataset/data/coin/annotations/videos/
